### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by mtx62** [SallaApp/Salla-CLI#32] opened 2023-08-21 07:51 UTC
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- 3.2.1

### Salla CLI issue Type

Theme

### Current Behavior

when executing `salla theme preview` I'm getting this error 

TypeError: Cannot read properties of undefined (reading 'length')

<img width="1028" alt="Screenshot 2023-08-21 at 10 46 28 AM" src="https://github.com/SallaApp/Salla-CLI/assets/3220251/e020b6b8-641f-432f-974f-a3f9d2b757bf">

### Expected Behavior

It should work and start showing the  theme preview

### Steps to Reproduce

executing `salla theme preview`

### Salla Info

[Salla info]
                     
version: 3.2.1
npm version: 9.8.0
node version: v16.14.0
/bin/sh: php: command not found
                     
 ERROR  Error: Command failed: php -v
/bin/sh: php: command not found

**Comment by medoasiri** [comment] 2023-08-23 20:11
Duplicate of # @

> 
Duplicate of #

**Comment by medoasiri** [comment] 2023-08-23 20:21
> ### Prerequisites
> 
> 
> 
> - [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.
> 
> 
> 
> ### SallaCLI Version
> 
> 
> 
> - 3.2.1
> 
> 
> 
> ### Salla CLI issue Type
> 
> 
> 
> Theme
> 
> 
> 
> ### Current Behavior
> 
> 
> 
> when executing `salla theme preview` I'm getting this error 
> 
> 
> 
> TypeError: Cannot read properties of undefined (reading 'length')
> 
> 
> 
> <img width="1028" alt="Screenshot 2023-08-21 at 10 46 28 AM" src="https://github.com/SallaApp/Salla-CLI/assets/3220251/e020b6b8-641f-432f-974f-a3f9d2b757bf">
> 
> 
> 
> 
> 
> ### Expected Behavior
> 
> 
> 
> It should work and start showing the  theme preview
> 
> 
> 
> ### Steps to Reproduce
> 
> 
> 
> executing `salla theme preview`
> 
> 
> 
> ### Code Reproduction URL
> 
> 
> 
> _No response_
> 
> 
> 
> ### Salla Info
> 
> 
> 
> [Salla info]
> 
>                      
> 
> version: 3.2.1
> 
> npm version: 9.8.0
> 
> node version: v16.14.0
> 
> /bin/sh: php: command not found
> 
>                      
> 
>  ERROR  Error: Command failed: php -v
> 
> /bin/sh: php: command not found
> 
> 
> 
> 
> 
> ### Additional Information
> 
> 
> 
> _No response_

**Comment by Nabute** [comment] 2023-08-27 07:50
@mtx62 this issue has already been resolved

**Closed** 2023-09-07 08:00 UTC
